In [1]:
import pandas as pd 
import numpy as np

In [2]:
# load npy file 
path = "./data_favour/datasets/ppmi_multi.npy"
data = np.load(path, allow_pickle=True)
path_corr = "./data_favour/correlation_matrices_processed.npy"
corr_matrices = np.load(path_corr, allow_pickle=True)
path_scores = "./data_favour/datasets/scores.npy"
scores = np.load(path_scores)
path_connectomes = "./data_favour/datasets/connectomes_0.npy"
connectomes = np.load(path_connectomes, allow_pickle=True)

In [3]:
data

array([(array([[-1.22319348e-01,  3.87638024e-01,  5.47339774e-01, ...,
               -2.06789209e-01,  2.77149182e-01, -2.81832271e-01],
              [ 4.91518757e-01, -1.88378330e-01,  8.84504751e-01, ...,
               -1.51775026e-01,  1.96550115e-01, -8.68018852e-02],
              [ 5.75503458e-01,  8.24390250e-01, -5.80145458e-02, ...,
               -6.31757927e-02,  2.99131956e-01, -1.94026140e-01],
              ...,
              [-1.50430945e-01, -1.61656092e-01,  3.55504572e-02, ...,
               -1.83649330e-01,  4.23522440e-01, -2.11933312e-01],
              [ 1.58461997e-01, -3.36412841e-04,  1.98597677e-01, ...,
                2.40608726e-01, -3.30185918e-02,  2.74454385e-03],
              [-3.43749278e-01, -2.14342377e-01, -1.87475558e-01, ...,
               -3.28647118e-01,  5.72836792e-02, -1.17911521e-01]]), tensor(1), '3130'),
       (array([[-0.12231935,  0.00744981,  0.08062633, ..., -0.19115784,
               -0.07977675, -0.26934483],
              [

In [4]:
# load xls file
path = "./data_favour/MDS_UPDRS/MDS_UPDRS_Part_III.xlsx"
xls = pd.read_excel(path)
xls.head()

PATNO PAG_NAME PDSTATE  DBS_STATUS  NP3SPCH  NP3FACXP  NP3RIGN  NP3RIGRU  \
0   3130  NUPDRS3     NaN         NaN      0.0       1.0      1.0       0.0   
1   3134  NUPDRS3     NaN         NaN      0.0       0.0      0.0       0.0   
2   3327  NUPDRS3     NaN         NaN      0.0       0.0      0.0       0.0   
3   3332  NUPDRS3     NaN         NaN      1.0       1.0      1.0       2.0   
4   3383  NUPDRS3     NaN         NaN      0.0       0.0      0.0       2.0   

   NP3RIGLU  NP3RIGRL  ...  NP3TOT  DYSKPRES  DYSKIRAT  NHY  PDTRTMNT  \
0       0.0       1.0  ...    10.0       0.0       NaN  1.0       0.0   
1       0.0       2.0  ...     8.0       0.0       NaN  1.0       0.0   
2       2.0       0.0  ...     7.0       0.0       NaN  1.0       0.0   
3       0.0       1.0  ...    14.0       0.0       NaN  1.0       0.0   
4       0.0       0.0  ...     9.0       0.0       NaN  2.0       0.0   

   DBSONTM  DBSOFFTM  HRPOSTMED  HRDBSOFF  HRDBSON  
0      NaN       NaN        NaN       NaN      NaN  
1      NaN       NaN        NaN       NaN      NaN  
2      NaN       NaN        NaN       NaN      NaN  
3      NaN       NaN        NaN       NaN      NaN  
4      NaN       NaN        NaN       NaN      NaN  

[5 rows x 47 columns]

In [5]:
xls.columns

Index(['PATNO', 'PAG_NAME', 'PDSTATE', 'DBS_STATUS', 'NP3SPCH', 'NP3FACXP',
       'NP3RIGN', 'NP3RIGRU', 'NP3RIGLU', 'NP3RIGRL', 'NP3RIGLL', 'NP3FTAPR',
       'NP3FTAPL', 'NP3HMOVR', 'NP3HMOVL', 'NP3PRSPR', 'NP3PRSPL', 'NP3TTAPR',
       'NP3TTAPL', 'NP3LGAGR', 'NP3LGAGL', 'NP3RISNG', 'NP3GAIT', 'NP3FRZGT',
       'NP3PSTBL', 'NP3POSTR', 'NP3BRADY', 'NP3PTRMR', 'NP3PTRML', 'NP3KTRMR',
       'NP3KTRML', 'NP3RTARU', 'NP3RTALU', 'NP3RTARL', 'NP3RTALL', 'NP3RTALJ',
       'NP3RTCON', 'NP3TOT', 'DYSKPRES', 'DYSKIRAT', 'NHY', 'PDTRTMNT',
       'DBSONTM', 'DBSOFFTM', 'HRPOSTMED', 'HRDBSOFF', 'HRDBSON'],
      dtype='object')

In [6]:
# load xls file
path = "./data_favour/MDS_UPDRS/PPMI_Data_Cohort.xlsx"
xls = pd.read_excel(path)
print(xls.columns)
print(len(xls))
xls.head()

Index(['PATNO', 'Group', 'Sex', 'Age', 'NP3GAIT'], dtype='object')
201


PATNO Group Sex  Age  NP3GAIT
0   3130    PD   M   44        1
1   3134    PD   M   39        1
2   3327    PD   F   54        0
3   3332    PD   M   74        0
4   3383    PD   M   48        0

In [7]:
# transform data to pandas dataframe
data = pd.DataFrame(data)

In [8]:
# change tensor labels type to int
data["labels"] = data["labels"].astype(int)
# make sure corr is a numpy array
data["corr"] = data["corr"].apply(lambda x: np.array(x).flatten())

In [9]:
data["labels"].value_counts()

labels
0    20
1     6
Name: count, dtype: int64

In [112]:
data.iloc[0]["corr"].shape

(27225,)

In [170]:
# simple Random Forest classification model using the correlation matrices in 'corr' and the labels in 'labels' column from 'data'
# 'corr' contain 165x165 matrices
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# split data into train and test
X_train, X_test, y_train, y_test = train_test_split(data["corr"], data["labels"], test_size=0.2, random_state=1)
X_train = list(X_train)
X_test = list(X_test)


# Rebalance the training data
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=42, k_neighbors=3)
X_train, y_train = sm.fit_resample(X_train, y_train)
print(len(X_train))
print(len(y_train))
print("Number of 0s: ", len(y_train[y_train==0]))
print("Number of 1s: ", len(y_train[y_train==1]))

# create a random forest classifier
clf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)

# train the classifier
clf.fit(X_train, y_train)

# predict labels for test data
y_pred = clf.predict(X_test)

# calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

30
30
Number of 0s:  15
Number of 1s:  15
Accuracy: 83.33%


In [171]:
y_test

18    0
13    0
17    0
3     0
22    1
10    0
Name: labels, dtype: int64

In [172]:
y_pred

array([0, 0, 0, 0, 0, 0])

In [173]:
# Use SVM classifier
from sklearn import svm
clf = svm.SVC()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
y_pred

Accuracy: 83.33%


array([0, 0, 0, 0, 0, 0])

In [179]:
# Use KNN classifier
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=20)
neigh.fit(X_train, y_train)
y_pred = neigh.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
y_pred

Accuracy: 50.00%


array([0, 0, 1, 1, 1, 1])

In [182]:
# Use MLP classifier
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(random_state=1, max_iter=500).fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
y_pred

Accuracy: 66.67%


array([0, 0, 1, 0, 0, 0])